project/masyarakat_view/urls.py
from django.urls import path
from .views import (
  UserDashboardView,

  PengaduanHistoryListView,
  PengaduanCreateView,
  PengaduanDeleteView,
)

urlpatterns = [
  path('' , UserDashboardView.as_view(), name="user_dashboard"),

  path('pengaduan/history/', PengaduanHistoryListView.as_view(), name="pengaduan_history"),
  path('pengaduan/create/<int:jenis_laporan_id>', PengaduanCreateView.as_view(), name="pengaduan_create"),
  path('pengaduan/delete/<int:pk>', PengaduanDeleteView.as_view(), name="pengaduan_delete"),
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(('auth_view.urls', 'auth_view') , namespace="auth")),
    path('' , include(('masyarakat_view.urls', 'masyarakat_view'), namespace="masyarakat")),
    path('petugas/', include(('petugas_view.urls', 'petugas_view'), namespace="petugas")),
    path('dinas/', include(('petugas_view.urls', 'petugas_view'), namespace="dinas")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/masyarakat_view/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils import timezone
from ckeditor.fields import RichTextField

from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils import timezone

class MasyarakatManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        if not username:
            raise ValueError("The Username field must be set")
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(username, password, **extra_fields)

class Masyarakat(AbstractBaseUser):
    username = models.CharField(max_length=25, unique=True)
    password = models.CharField(max_length=128)
    alamat = models.TextField()
    kecamatan = models.CharField(max_length=35)
    telp = models.CharField(max_length=13)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    last_login = models.DateTimeField(auto_now=True)

    objects = MasyarakatManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['alamat', 'kecamatan', 'telp']

    class Meta:
        verbose_name = "Masyarakat"
        verbose_name_plural = "Masyarakat"

    def __str__(self):
        return self.username

    def set_password(self, raw_password):
        super().set_password(raw_password)

    def check_password(self, raw_password):
        return super().check_password(raw_password)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.last_login = timezone.now()
        super().save(*args, **kwargs)

    def has_perm(self, perm, obj=None):
        return self.is_staff

    def has_module_perms(self, app_label):
        return self.is_staff

class Jenis_Laporan(models.Model):
    foto = models.ImageField(upload_to="gambar_jenis_laporan/")
    jenis = models.CharField(max_length=32)

    def __str__(self):
        return self.jenis

class Pengaduan(models.Model):
    tgl_pengaduan = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(Masyarakat, on_delete=models.CASCADE)
    isi_aduan = RichTextField()
    foto = models.ImageField(upload_to="gambar_pengaduan/")
    dinas = models.ForeignKey('dinas_view.Dinas', on_delete=models.CASCADE)

    jenis_laporan = models.ForeignKey(Jenis_Laporan, on_delete=models.SET_NULL, null=True, blank=True)

    class Status(models.TextChoices):
        BELUM_TERJAWAB = '0', 'Belum Terjawab'
        DESPOSISI = 'desposisi', 'Desposisi'
        PROSES = 'proses', 'Proses'
        SELESAI = 'selesai', 'Selesai'
        TOLAK = 'tolak', 'Tolak'

    status = models.CharField(max_length=10, choices=Status.choices, default=Status.BELUM_TERJAWAB, blank=True, null=True)

    class Meta:
        verbose_name = "Pengaduan"
        verbose_name_plural = "Pengaduan"

    def __str__(self):
        return f"Pengaduan oleh {self.user.username} - Status: {self.get_status_display()}"

    @property
    def tanggapan(self):
        return self.tanggapan_set.first()

project/petugas_view/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils import timezone
from django.contrib.auth.hashers import check_password, make_password

class PetugasManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        if not username:
            raise ValueError("The Username field must be set")
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(username, password, **extra_fields)

class Petugas(AbstractBaseUser):
    nama = models.CharField(max_length=35)
    username = models.CharField(max_length=25, unique=True)
    password = models.CharField(max_length=128)
    level = models.CharField(max_length=10, choices=[('admin', 'Admin'), ('petugas', 'Petugas')], default='petugas', null=True, blank=True)
    telp = models.CharField(max_length=13)
    dinas = models.ForeignKey('dinas_view.Dinas', on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    last_login = models.DateTimeField(auto_now=True)

    objects = PetugasManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['level']

    class Meta:
        verbose_name = "Petugas"
        verbose_name_plural = "Petugas"

    def __str__(self):
        return self.username

    def set_password(self, raw_password):
        super().set_password(raw_password)

    def check_password(self, raw_password):
        return super().check_password(raw_password)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.last_login = timezone.now()
        super().save(*args, **kwargs)

    def has_perm(self, perm, obj=None):
        return self.is_staff

    def has_module_perms(self, app_label):
        return self.is_staff

class Log_Aktivitas(models.Model):
  petugas = models.ForeignKey(Petugas, on_delete=models.CASCADE)
  aktifitas = models.CharField(max_length=255)
  tanggal = models.DateTimeField(default=timezone.now())

  class Meta:
    verbose_name = "Log Aktifitas"
    verbose_name_plural = "Log Aktifitas"
    ordering = ['-tanggal']

  def __str__(self):
    return f"Petugas: {self.petugas}, Aktivitas: {self.aktifitas}, Tanggal: {self.tanggal.strftime('%Y-%m-%d %H:%M:%S')}"

class Tanggapan(models.Model):
  pengaduan = models.ForeignKey('masyarakat_view.Pengaduan', on_delete=models.CASCADE)
  tgl_tanggapan = models.DateTimeField(auto_now_add=True)
  tanggapan = RichTextField()

  petugas = models.ForeignKey(Petugas, on_delete=models.CASCADE)

  class Status(models.TextChoices):
    BELUM_TERJAWAB = '0', 'Belum Terjawab'
    DESPOSISI = 'desposisi', 'Desposisi'
    PROSES = 'proses', 'Proses'
    SELESAI = 'selesai', 'Selesai'
    TOLAK = 'tolak', 'Tolaks'

  status = models.CharField(max_length=9, choices=Status.choices, default=Status.BELUM_TERJAWAB)

  class Meta:
    verbose_name = 'Tanggapan'
    verbose_name_plural = 'Tanggapan'

  def __str__(self):
    return f'Tanggapan Pengaduan pada {self.pengaduan.isi_aduan[:50]}'

project/masyarakat_view/forms.py
from django import forms
from .models import Pengaduan
from dinas_view.models import Dinas
from django.forms import ModelForm

class PengaduanForm(ModelForm):
    class Meta:
        model = Pengaduan
        fields = ['isi_aduan', 'foto', 'dinas']

    isi_aduan = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-input px-4 py-2 border w-full border w-full-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-lime-500',
        'rows': 4,
        'placeholder': 'Tulis aduan Anda di sini'
    }))
    foto = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={
        'class': 'form-input py-2 px-4 border w-full border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-lime-500'
    }))
    dinas = forms.ModelChoiceField(queryset=Dinas.objects.all(), widget=forms.Select(attrs={
        'class': 'form-input py-2 px-4 border w-full border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-lime-500'
    }))

project/masyarakat_view/views.py
from typing import Any
from django.urls import reverse_lazy
from django.views.generic import (
  ListView,
  CreateView,
  DeleteView,
)
from django.shortcuts import get_object_or_404, redirect
from .forms import PengaduanForm
from .models import (
  Masyarakat,
  Jenis_Laporan,
  Pengaduan,
)
from petugas_view.models import (
  Petugas
)
from dinas_view.models import Dinas

class UserDashboardView(ListView):
  model = Jenis_Laporan
  template_name = "masyarakat/dashboard.html"
  context_object_name = 'jenis_laps'

  def get(self,request):
    if not self.request.user.is_authenticated:
      return redirect('auth:user_login')

    user = self.request.user
    if isinstance(user, Petugas):
      return redirect('petugas:petugas_dashboard')
    return super().get(request)

  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context["judul"] = "Dashboard Pengaduan Masyarakat"
      context["header"] = "Dashboard Masyarakat"
      context["dinas_all"] = Dinas.objects.all()
      return context

class PengaduanHistoryListView(ListView):
  model = Pengaduan
  template_name = 'masyarakat/pengaduan_history.html'
  context_object_name = "pengaduans"

  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context["judul"] = "Histori Pengaduan Page"
      context['header'] = "Dashboard Masyarakat"
      context["pengaduans"] = Pengaduan.objects.filter(user=self.request.user.pk).order_by('-tgl_pengaduan')
      return context

class PengaduanCreateView(CreateView):
    model = Pengaduan
    template_name = "masyarakat/pengaduan_form.html"
    form_class = PengaduanForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['judul'] = "Pengaduan Create Page"

        jenis_laporan_id = self.kwargs.get('jenis_laporan_id')
        jenis_laporan = get_object_or_404(Jenis_Laporan, id=jenis_laporan_id)
        context['jenis_laporan'] = jenis_laporan

        return context

    def form_valid(self, form):
        jenis_laporan_id = self.kwargs.get('jenis_laporan_id')
        jenis_laporan = get_object_or_404(Jenis_Laporan, id=jenis_laporan_id)

        user = self.request.user
        if isinstance(user, Masyarakat):
            form.instance.user = user
            form.instance.jenis_laporan = jenis_laporan
            return super().form_valid(form)
        else:
            return redirect('masyarakat:user_login')

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('auth:user_login')

        user = self.request.user
        if isinstance(user, Petugas):
            return redirect('petugas:petugas_dashboard')

        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('masyarakat:user_dashboard')

class PengaduanDeleteView(DeleteView):
    model = Pengaduan

    def get_success_url(self):
      return reverse_lazy('masyarakat:pengaduan_history')

project/masyarakat_view/templates/masyarakat/dashboard.html
{% include 'base.html' %}

{% block contents %}

<div class="bg-lime-200 min-h-screen py-8">
  {% include 'snippets/nav_user.html' %}
  <div class="container mx-auto text-center mt-12">
    <h2 class="text-3xl font-bold text-gray-800 mb-8">Pilih Jenis Pelaporan:</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6">
      {% for jenis_lap in jenis_laps %}
        <a href="{% url 'masyarakat:pengaduan_create' jenis_lap.id %}" class="flex items-center bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition transform hover:scale-105">
          <img src="{{ jenis_lap.foto.url }}" alt="{{ jenis_lap.jenis }}" class="w-16 h-16 mr-4">

          <p class="text-xl font-semibold text-gray-800">{{ jenis_lap.jenis }}</p>
        </a>
      {% endfor %}
    </div>
  </div>

  <!-- Telepon Darurat -->
  <div class="bg-white mt-16 py-8">
    <div class="container mx-auto text-center">
      <h2 class="text-3xl font-bold text-lime-600 mb-4">Telepon Darurat</h2>
      <p class="text-lg text-gray-600 mb-8">Hubungi nomor dibawah ini jika keadaan dirasa darurat</p>
      <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-6">
        {% for dinas in dinas_all %}
          <div class="p-4 bg-lime-100 rounded-lg shadow-md hover:shadow-lg">
            <p class="text-xl font-semibold text-lime-800">{{ dinas.nama }}</p>
            <a href="tel:%{{dinas.telp}}" class="text-lg text-gray-700">{{ dinas.telp }}</a>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

<!-- Footer -->
<footer class="bg-zinc-600 text-white text-center py-3">
  <p>Pengaduan Masyarakat by <a href="https://github.com/yusrb" target="__blank">yusrb</a></p>
</footer>
{% endblock %}

project/masyarakat_view/templates/masyarakat/pengaduan_form.html
{% include 'base.html' %} {% block contents %}
<div class="text-center mt-8">
  <h1 class="text-3xl font-semibold text-gray-800">Buat Pengaduan</h1>
</div>

<div class="container mx-auto p-6 bg-white rounded-lg shadow-md mt-8">
  <div class="w-full text-center bg-lime-100 p-4 rounded-md mb-6">
    <p class="text-xl font-semibold text-lime-800">{{ jenis_laporan.jenis }}</p>
  </div>

  <hr class="border-t-8 rounded-lg border-lime-500 my-3">

  <form action="" method="post" enctype="multipart/form-data" class="space-y-6">
    {% csrf_token %}

    <div>
      <label
        for="isi_aduan"
        class="block text-lg font-semibold text-gray-700 mb-2"
        >Isi Aduan</label
      >
      {{ form.isi_aduan }}
    </div>

    <div>
      <label for="foto" class="block text-lg font-semibold text-gray-700 mb-2"
        >Foto (Optional)</label
      >
      {{ form.foto }}
    </div>

    <div>
      <label for="dinas" class="block text-lg font-semibold text-gray-700 mb-2"
        >Pilih Dinas</label
      >
      {{ form.dinas }}
    </div>

    <div>
      <button
        type="submit"
        class="w-full bg-lime-500 text-white font-bold py-2 rounded-md hover:bg-lime-600 transition"
      >
        Kirim Pengaduan
      </button>
    </div>
  </form>

  <div class="mt-6 text-center">
    <a
      href="{% url 'masyarakat:user_dashboard' %}"
      class="text-lime-500 hover:underline"
      >Kembali ke Dashboard</a
    >
  </div>
</div>
{% endblock %}

project/masyarakat_view/templates/masyarakat/pengaduan_history.html
{% include 'base.html' %} {% block contents %}
<div class="bg-lime-200 min-h-screen py-8">
  {% include 'snippets/nav_user.html' %}

  <div class="container mx-auto text-center mt-12">
    <h2 class="text-3xl font-bold text-gray-800 mb-8">History Pengaduan</h2>
  </div>

  <div class="container mx-auto">
    <div class="space-y-8">
      {% for pengaduan in pengaduans %}
      <div
        class="relative flex items-center bg-white rounded-lg shadow-md p-6 hover:shadow-lg transition"
      >
        <div class="w-1/3">
          <img
            class="w-full h-60 rounded-md object-cover"
            src="{{ pengaduan.foto.url }}"
            alt="{{ pengaduan.isi_aduan|truncatechars:30 }}"
          />
        </div>

        <div class="w-2/3 ml-6">
          <p class="text-gray-700 text-lg">
            <span class="font-bold">Tanggal:</span> {{ pengaduan.tgl_pengaduan}}
          </p>
          <p class="text-gray-700 text-lg">
            <span class="font-bold">Jenis Laporan:</span> {{pengaduan.jenis_laporan }}
          </p>
          <p class="text-gray-700 text-lg">
            <span class="font-bold">Isi Laporan:</span> {{ pengaduan.isi_aduan}}
          </p>

          {% if pengaduan.tanggapan_set.exists %}
          <div class="mt-2">
            <p class="font-bold text-gray-800">Tanggapan:</p>
            <ul class="list-disc list-inside text-gray-700">
              {% for tanggapan in pengaduan.tanggapan_set.all %}
              <li>
                {{ tanggapan.tanggapan }} - {{ tanggapan.petugas.username }} ({{tanggapan.tgl_tanggapan }})
              </li>
              {% endfor %}
            </ul>
          </div>
          {% else %}
          <p class="text-gray-600 italic">Belum ada tanggapan.</p>
          {% endif %}

          <p class="mt-4 relative right-1 text-right text-lime-700 font-semibold text-lg">
            Status: {{ pengaduan.status }}
          </p>
        </div>

        <div class="absolute top-0 right-0 p-4">
          <form
            action="{% url 'masyarakat:pengaduan_delete' pengaduan.pk %}"
            method="post"
            id="delete-form-{{ pengaduan.pk }}"
          >
            {% csrf_token %}
            <button
              type="submit"
              onclick="return confirmDelete({{ pengaduan.pk }})"
              class="text-red-600 font-bold hover:text-red-800 transition"
              title="Hapus Pengaduan"
            >
              ✕
            </button>
          </form>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

<footer class="bg-zinc-600 text-white text-center py-3 mt-10">
  <p>
    Pengaduan Masyarakat by
    <a href="https://github.com/yusrb" target="__blank" class="underline"
      >yusrb</a
    >
  </p>
</footer>

<script>
  function confirmDelete(pengaduanId) {
    return confirm("Apakah Anda yakin ingin menghapus pengaduan ini?");
  }
</script>
{% endblock %}