project/petugas_view/urls.py
from django.urls import path
from .views import (
    PengaduanBelumTerjawabListView,
    TanggapanBelumTerjawabCreateView,
    PengaduanDesposisiListView,
    TanggapanDesposisiCreateView,
    PengaduanProsesListView,
    TanggapanProsesCreateView,
    PengaduanSelesaiListView,
    PengaduanTolakListView,
    TanggapanTolakView,
    TanggapanSelesaiCreateView,

    LogAktivitasPetugasListView,

    buat_pengaduan_dokumen,
)

urlpatterns = [
    path('', PengaduanBelumTerjawabListView.as_view(), name='petugas_dashboard'),
    path('tanggapan/belum-terjawab/<int:pengaduan_id>/', TanggapanBelumTerjawabCreateView.as_view(), name='tanggapan_belum_terjawab'),
    path('pengaduan/desposisi/', PengaduanDesposisiListView.as_view(), name='pengaduan_desposisi_view'),
    path('tanggapan/desposisi/<int:pengaduan_id>/', TanggapanDesposisiCreateView.as_view(), name='tanggapan_desposisi'),
    path('pengaduan/proses/', PengaduanProsesListView.as_view(), name='pengaduan_proses_view'),
    path('tanggapan/proses/<int:pengaduan_id>/', TanggapanProsesCreateView.as_view(), name='tanggapan_proses'),
    path('pengaduan/selesai/', PengaduanSelesaiListView.as_view(), name='pengaduan_selesai_view'),
    path('tanggapan/selesai/<int:pengaduan_id>/', TanggapanSelesaiCreateView.as_view(), name='tanggapan_selesai'),
    path('pengaduan/tolak/', PengaduanTolakListView.as_view(), name='pengaduan_tolak_view'),
    path('pengaduan/tanggapan/tolak/<int:pengaduan_id>/', TanggapanTolakView.as_view(), name='tanggapan_tolak'),

    path('log_aktivitas/' , LogAktivitasPetugasListView.as_view(), name="log_aktivitas_view"),

    path('pengaduan/generate_pdf/', buat_pengaduan_dokumen, name='buat_pengaduan_dokumen'),
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(('auth_view.urls', 'auth_view') , namespace="auth")),
    path('' , include(('masyarakat_view.urls', 'masyarakat_view'), namespace="masyarakat")),
    path('petugas/', include(('petugas_view.urls', 'petugas_view'), namespace="petugas")),
    path('dinas/', include(('petugas_view.urls', 'petugas_view'), namespace="dinas")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/petugas_view/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils import timezone
from django.contrib.auth.hashers import check_password, make_password

class PetugasManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        if not username:
            raise ValueError("The Username field must be set")
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(username, password, **extra_fields)

class Petugas(AbstractBaseUser):
    nama = models.CharField(max_length=35)
    username = models.CharField(max_length=25, unique=True)
    password = models.CharField(max_length=128)
    level = models.CharField(max_length=10, choices=[('admin', 'Admin'), ('petugas', 'Petugas')], default='petugas', null=True, blank=True)
    telp = models.CharField(max_length=13)
    dinas = models.ForeignKey('dinas_view.Dinas', on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    last_login = models.DateTimeField(auto_now=True)

    objects = PetugasManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['level']

    class Meta:
        verbose_name = "Petugas"
        verbose_name_plural = "Petugas"

    def __str__(self):
        return self.username

    def set_password(self, raw_password):
        super().set_password(raw_password)

    def check_password(self, raw_password):
        return super().check_password(raw_password)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.last_login = timezone.now()
        super().save(*args, **kwargs)

    def has_perm(self, perm, obj=None):
        return self.is_staff

    def has_module_perms(self, app_label):
        return self.is_staff

class Log_Aktivitas(models.Model):
  petugas = models.ForeignKey(Petugas, on_delete=models.CASCADE)
  aktifitas = models.CharField(max_length=255)
  tanggal = models.DateTimeField(default=timezone.now())

  class Meta:
    verbose_name = "Log Aktifitas"
    verbose_name_plural = "Log Aktifitas"
    ordering = ['-tanggal']

  def __str__(self):
    return f"Petugas: {self.petugas}, Aktivitas: {self.aktifitas}, Tanggal: {self.tanggal.strftime('%Y-%m-%d %H:%M:%S')}"

class Tanggapan(models.Model):
  pengaduan = models.ForeignKey('masyarakat_view.Pengaduan', on_delete=models.CASCADE)
  tgl_tanggapan = models.DateTimeField(auto_now_add=True)
  tanggapan = RichTextField()

  petugas = models.ForeignKey(Petugas, on_delete=models.CASCADE)

  class Status(models.TextChoices):
    BELUM_TERJAWAB = '0', 'Belum Terjawab'
    DESPOSISI = 'desposisi', 'Desposisi'
    PROSES = 'proses', 'Proses'
    SELESAI = 'selesai', 'Selesai'
    TOLAK = 'tolak', 'Tolaks'

  status = models.CharField(max_length=9, choices=Status.choices, default=Status.BELUM_TERJAWAB)

  class Meta:
    verbose_name = 'Tanggapan'
    verbose_name_plural = 'Tanggapan'

  def __str__(self):
    return f'Tanggapan Pengaduan pada {self.pengaduan.isi_aduan[:50]}'

project/petugas_view/forms.py
from django import forms
from .models import Tanggapan

class TanggapanForm(forms.ModelForm):
    class Meta:
        model = Tanggapan
        fields = ['tanggapan',]

    tanggapan = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm hover:ring-lime-200  focus:outline-none focus:ring-lime-200 focus:border-lime-200',
        'rows': 5,
        'placeholder': 'Tulis tanggapan di sini...'
    }), required=True)

project/petugas_view/views.py
from typing import Any
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.http import HttpResponse
from weasyprint import HTML
from django.template.loader import render_to_string
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView
from masyarakat_view.models import Masyarakat, Pengaduan
from .models import Petugas, Tanggapan, Log_Aktivitas
from .forms import TanggapanForm

class PengaduanBelumTerjawabListView(ListView):
    model = Pengaduan
    template_name = "petugas/pengaduan_belum_terjawab.html"
    context_object_name = "pengaduans"

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('auth:petugas_login')

        user = self.request.user
        if isinstance(user, Masyarakat):
            return redirect('masyarakat:user_dashboard')

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['judul'] = "Pengaduan Belum Terjawab"
        context['pengaduans'] = Pengaduan.objects.filter(status=Pengaduan.Status.BELUM_TERJAWAB)
        return context

class TanggapanBelumTerjawabCreateView(CreateView):
    model = Tanggapan
    fields = ['tanggapan']
    template_name = 'petugas/tanggapan_form.html'

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated and self.request.user.level == 'petugas' or self.request.user.level == 'admin':
            pengaduan_id = self.kwargs.get('pengaduan_id')
            pengaduan = get_object_or_404(Pengaduan, pk=pengaduan_id)

            if pengaduan.status != Pengaduan.Status.BELUM_TERJAWAB:
                return redirect('petugas:petugas_dashboard')

            return super().get(request, *args, **kwargs)
        else:
            return redirect('auth:petugas_login')

    def form_valid(self, form):
        tanggapan = form.save(commit=False)

        pengaduan_id = self.kwargs.get('pengaduan_id')
        pengaduan = get_object_or_404(Pengaduan, pk=pengaduan_id)

        tanggapan.pengaduan = pengaduan
        tanggapan.petugas = self.request.user

        pengaduan.status = Pengaduan.Status.DESPOSISI
        tanggapan.status = Tanggapan.Status.DESPOSISI

        tanggapan.save()
        pengaduan.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('petugas:petugas_dashboard')

class PengaduanDesposisiListView(ListView):
    model = Pengaduan
    template_name = "petugas/pengaduan_desposisi.html"
    context_object_name = "pengaduans"

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('auth:petugas_login')

        user = self.request.user
        if isinstance(user, Masyarakat):
            return redirect('masyarakat:user_dashboard')

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['judul'] = "Pengaduan Desposisi"
        context['pengaduans'] = Pengaduan.objects.filter(status=Pengaduan.Status.DESPOSISI)
        return context

class TanggapanDesposisiCreateView(CreateView):
    model = Tanggapan
    form_class = TanggapanForm
    template_name = 'petugas/tanggapan_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['judul'] = "Desposisi Form Page"
        pengaduan_id = self.kwargs['pengaduan_id']
        pengaduan = get_object_or_404(Pengaduan, id=pengaduan_id)

        context['pengaduan'] = pengaduan
        return context

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated and self.request.user.level == 'petugas' or self.request.user.level == 'admin':
            pengaduan_id = self.kwargs.get('pengaduan_id')
            pengaduan = get_object_or_404(Pengaduan, pk=pengaduan_id)

            if pengaduan.status != Pengaduan.Status.DESPOSISI:
                return redirect('petugas:petugas_dashboard')

            return super().get(request, *args, **kwargs)
        else:
            return redirect('auth:petugas_login')

    def form_valid(self, form):
        tanggapan = form.save(commit=False)

        pengaduan_id = self.kwargs.get('pengaduan_id')
        pengaduan = get_object_or_404(Pengaduan, pk=pengaduan_id)

        tanggapan.pengaduan = pengaduan
        tanggapan.petugas = self.request.user

        pengaduan.status = Pengaduan.Status.PROSES
        tanggapan.status = Tanggapan.Status.PROSES

        tanggapan.save()
        pengaduan.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('petugas:petugas_dashboard')

class PengaduanProsesListView(ListView):
    model = Pengaduan
    template_name = "petugas/pengaduan_proses.html"
    context_object_name = "pengaduans"

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('auth:petugas_login')

        user = self.request.user
        if isinstance(user, Masyarakat):
            return redirect('masyarakat:user_dashboard')

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['judul'] = "Pengaduan Proses"
        context['pengaduans'] = Pengaduan.objects.filter(status=Pengaduan.Status.PROSES)
        return context

class TanggapanProsesCreateView(CreateView):
    model = Tanggapan
    form_class = TanggapanForm
    template_name = 'petugas/tanggapan_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["judul"] = "Tanggapan Proses Page"
        pengaduan_id = self.kwargs['pengaduan_id']
        pengaduan = get_object_or_404(Pengaduan, id=pengaduan_id)

        context['pengaduan'] = pengaduan
        return context
    

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated and self.request.user.level == 'petugas' or self.request.user.level == 'admin':
            pengaduan_id = self.kwargs.get('pengaduan_id')
            pengaduan = get_object_or_404(Pengaduan, pk=pengaduan_id)

            if pengaduan.status != Pengaduan.Status.PROSES:
                return redirect('petugas:petugas_dashboard')

            return super().get(request, *args, **kwargs)
        else:
            return redirect('auth:petugas_login')

    def form_valid(self, form):
        tanggapan = form.save(commit=False)

        pengaduan_id = self.kwargs.get('pengaduan_id')
        pengaduan = get_object_or_404(Pengaduan, pk=pengaduan_id)

        tanggapan.pengaduan = pengaduan
        tanggapan.petugas = self.request.user

        pengaduan.status = Pengaduan.Status.SELESAI
        tanggapan.status = Tanggapan.Status.SELESAI

        tanggapan.save()
        pengaduan.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('petugas:petugas_dashboard')

class PengaduanSelesaiListView(ListView):
    model = Pengaduan
    template_name = "petugas/pengaduan_selesai.html"
    context_object_name = "pengaduans"

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('auth:petugas_login')

        user = self.request.user
        if isinstance(user, Masyarakat):
            return redirect('masyarakat:user_dashboard')

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['judul'] = "Pengaduan Selesai"
        context['pengaduans'] = Pengaduan.objects.filter(status=Pengaduan.Status.SELESAI)
        return context

class PengaduanTolakListView(ListView):
    model = Pengaduan
    template_name = "petugas/pengaduan_tolak.html"
    context_object_name = "pengaduans"

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('auth:petugas_login')

        user = self.request.user
        if isinstance(user, Masyarakat):
            return redirect('masyarakat:user_dashboard')

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['judul'] = "Pengaduan Tolak"
        context['pengaduans'] = Pengaduan.objects.filter(status=Pengaduan.Status.TOLAK)
        return context

class TanggapanTolakView(UpdateView):
    model = Pengaduan
    template_name = 'petugas/tanggapan_tolak.html'
    context_object_name = 'pengaduan'
    form_class = TanggapanForm

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('auth:petugas_login')

        user = self.request.user
        if isinstance(user, Masyarakat):
            return redirect('masyarakat:user_dashboard')

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["judul"] = "Validasi Kembali Page"
        return context

    def get_object(self):
        pengaduan = get_object_or_404(Pengaduan, id=self.kwargs['pengaduan_id'], status=Pengaduan.Status.TOLAK)
        return pengaduan

    def form_valid(self, form):
        pengaduan = form.save(commit=False)
        pengaduan.status = Pengaduan.Status.SELESAI
        pengaduan.petugas = self.request.user
        pengaduan.save()
        return redirect('petugas:pengaduan_tolak_view')

class TanggapanSelesaiCreateView(CreateView):
    model = Tanggapan
    form_class = TanggapanForm
    template_name = 'petugas/tanggapan_form.html'

    def get_context_data(self, **kwargs):

project/petugas_view/templates/petugas/pengaduan_belum_terjawab.html
{% extends "base.html" %}
{% block contents %}
{% include 'snippets/nav_admin.html' %}

<!-- Heading Section -->
<div class="container mx-auto p-6">
  <h1 class="text-3xl font-semibold text-gray-900 text-center mb-6">{{ judul }}</h1>

  <!-- Pengaduan List -->
  <div class="space-y-6">
    {% for pengaduan in pengaduans %}
    <div class="bg-white shadow-lg rounded-lg p-6 flex flex-col md:flex-row gap-6 mb-6">
      <!-- Left Side: Image -->
      <div class="w-full md:w-1/4">
        <img src="{{ pengaduan.foto.url }}" alt="Foto Aduan" class="w-full h-48 object-cover rounded-md shadow-sm">
      </div>

      <!-- Right Side: Information -->
      <div class="flex-1">
        <p class="text-xl font-semibold text-gray-900 mb-2">{{ pengaduan.isi_aduan|safe }}</p>
        <p class="text-gray-700 mb-1"><strong>Status:</strong> {{ pengaduan.get_status_display }}</p>
        <p class="text-gray-700 mb-1"><strong>Pengadu:</strong> {{ pengaduan.user.username }}</p>
        <p class="text-gray-700 mb-1"><strong>Tanggal Pengaduan:</strong> {{ pengaduan.tgl_pengaduan }}</p>
        <p class="text-gray-700 mb-1"><strong>Instansi:</strong> {{ pengaduan.dinas.nama }}</p>
        <p class="text-gray-700 mb-4"><strong>Jenis Laporan:</strong> {{ pengaduan.jenis_laporan }}</p>

        <div class="flex justify-end">
          <a href="{% url 'petugas:tanggapan_belum_terjawab' pengaduan_id=pengaduan.id %}"
             class="bg-lime-600 text-white px-4 py-3 rounded-md hover:bg-lime-700 transition duration-300 ease-in-out">
            Tanggapi
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

project/petugas_view/templates/petugas/pengaduan_desposisi.html
{% extends "base.html" %}
{% block contents %}
{% include 'snippets/nav_admin.html' %}

<!-- Heading Section -->
<div class="container mx-auto p-6">
  <h1 class="text-3xl font-semibold text-gray-900 text-center mb-8">{{ judul }}</h1>

  <!-- Pengaduan List -->
  <div class="space-y-6">
    {% for pengaduan in pengaduans %}
    <div class="bg-white shadow-lg rounded-lg p-6 flex flex-col md:flex-row gap-6 mb-6">
      
      <div class="w-full md:w-1/4">
        <img src="{{ pengaduan.foto.url }}" alt="Foto Aduan" class="w-full h-48 object-cover rounded-md shadow-sm">
      </div>

      <div class="flex-1">
        <p class="text-xl font-semibold text-gray-900 mb-2">{{ pengaduan.isi_aduan|safe }}</p>
        <p class="text-gray-700 mb-1"><strong>Status:</strong> {{ pengaduan.get_status_display }}</p>
        <p class="text-gray-700 mb-1"><strong>Pengadu:</strong> {{ pengaduan.user.username }}</p>
        <p class="text-gray-700 mb-1"><strong>Tanggal Pengaduan:</strong> {{ pengaduan.tgl_pengaduan }}</p>
        <p class="text-gray-700 mb-1"><strong>Instansi:</strong> {{ pengaduan.dinas.nama }}</p>
        <p class="text-gray-700 mb-4"><strong>Jenis Laporan:</strong> {{ pengaduan.jenis_laporan }}</p>

        <div class="flex justify-end">
          <a href="{% url 'petugas:tanggapan_desposisi' pengaduan_id=pengaduan.id %}"
        class="bg-lime-600 text-white px-4 py-3 rounded-md hover:bg-lime-700 transition duration-300 ease-in-out">
            Tanggapi
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

project/petugas_view/templates/petugas/pengaduan_proses.html
{% extends "base.html" %}
{% block contents %}
{% include 'snippets/nav_admin.html' %}

<div class="container mx-auto p-6">
  <h1 class="text-3xl font-semibold text-gray-900 text-center mb-8">{{ judul }}</h1>

  <div class="space-y-6">
    {% for pengaduan in pengaduans %}
    <div class="bg-white shadow-lg rounded-lg p-6 flex flex-col md:flex-row gap-6 mb-6">
      <div class="w-full md:w-1/4">
        <img src="{{ pengaduan.foto.url }}" alt="Foto Aduan" class="w-full h-48 object-cover rounded-md shadow-sm">
      </div>

      <div class="flex-1">
        <p class="text-xl font-semibold text-gray-900 mb-2">{{ pengaduan.isi_aduan|safe }}</p>
        <p class="text-gray-700 mb-1"><strong>Status:</strong> {{ pengaduan.get_status_display }}</p>
        <p class="text-gray-700 mb-1"><strong>Pengadu:</strong> {{ pengaduan.user.username }}</p>
        <p class="text-gray-700 mb-1"><strong>Tanggal Pengaduan:</strong> {{ pengaduan.tgl_pengaduan }}</p>
        <p class="text-gray-700 mb-1"><strong>Instansi:</strong> {{ pengaduan.dinas.nama }}</p>
        <p class="text-gray-700 mb-4"><strong>Jenis Laporan:</strong> {{ pengaduan.jenis_laporan }}</p>

        <div class="flex justify-end">
          <a href="{% url 'petugas:tanggapan_proses' pengaduan_id=pengaduan.id %}" 
             class="bg-lime-600 text-white px-4 py-3 rounded-md hover:bg-lime-700 transition duration-300 ease-in-out">
            Tanggapi
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

project/petugas_view/templates/petugas/pengaduan_selesai.html
{% extends "base.html" %}
{% block contents %}
{% include 'snippets/nav_admin.html' %}

<!-- Heading Section -->
<div class="container mx-auto p-6">
  <h1 class="text-3xl font-semibold text-gray-900 text-center mb-8">{{ judul }}</h1>

  {% if request.user.level == 'admin' %}
  <div class="mb-6 text-center">
    <a href="{% url 'petugas:buat_pengaduan_dokumen' %}" 
       class="bg-lime-600 text-white px-8 py-3 rounded-md hover:bg-gray-900 transition duration-300 ease-in-out">
      Buat Dokumen PDF
    </a>
  </div>
  {% endif %}

  <!-- Pengaduan List -->
  <div class="space-y-6">
    {% for pengaduan in pengaduans %}
    <div class="bg-white shadow-lg rounded-lg p-6 flex flex-col md:flex-row gap-6 mb-6">
      <!-- Left Side: Image -->
      <div class="w-full md:w-1/4">
        <img src="{{ pengaduan.foto.url }}" alt="Foto Aduan" class="w-full h-48 object-cover rounded-md shadow-sm">
      </div>

      <!-- Right Side: Information -->
      <div class="flex-1">
        <p class="text-xl font-semibold text-gray-900 mb-2">{{ pengaduan.isi_aduan|safe }}</p>
        <p class="text-gray-700 mb-1"><strong>Status:</strong> {{ pengaduan.get_status_display }}</p>
        <p class="text-gray-700 mb-1"><strong>Pengadu:</strong> {{ pengaduan.user.username }}</p>
        <p class="text-gray-700 mb-1"><strong>Tanggal Pengaduan:</strong> {{ pengaduan.tgl_pengaduan }}</p>
        <p class="text-gray-700 mb-1"><strong>Instansi:</strong> {{ pengaduan.dinas.nama }}</p>
        <p class="text-gray-700 mb-4"><strong>Jenis Laporan:</strong> {{ pengaduan.jenis_laporan }}</p>

        <!-- Action Button -->
        <div class="flex justify-end">
          <a href="{% url 'petugas:tanggapan_selesai' pengaduan_id=pengaduan.id %}"
             class="bg-red-600 text-white px-5 py-3 rounded-md hover:bg-red-700 transition duration-300 ease-in-out">
            Tolak
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

project/petugas_view/templates/petugas/pengaduan_tolak.html
{% extends "base.html" %}
{% block contents %}
{% include 'snippets/nav_admin.html' %}

<div class="container mx-auto p-6">
  
  <h1 class="text-3xl font-semibold text-gray-900 text-center mb-8">{{ judul }}</h1>
  <div class="space-y-6">
    {% for pengaduan in pengaduans %}
    <div class="bg-white shadow-lg rounded-lg p-6 flex flex-col md:flex-row gap-6 mb-6">
      <div class="w-full md:w-1/4">
        <img src="{{ pengaduan.foto.url }}" alt="Foto Aduan" class="w-full h-48 object-cover rounded-md shadow-sm">
      </div>

      <div class="flex-1">
        <p class="text-xl font-semibold text-gray-900 mb-2">{{ pengaduan.isi_aduan|safe }}</p>
        <p class="text-gray-700 mb-1"><strong>Status:</strong> {{ pengaduan.get_status_display }}</p>
        <p class="text-gray-700 mb-1"><strong>Pengadu:</strong> {{ pengaduan.user.username }}</p>
        <p class="text-gray-700 mb-1"><strong>Tanggal Pengaduan:</strong> {{ pengaduan.tgl_pengaduan }}</p>
        <p class="text-gray-700 mb-1"><strong>Instansi:</strong> {{ pengaduan.dinas.nama }}</p>
        <p class="text-gray-700 mb-4"><strong>Jenis Laporan:</strong> {{ pengaduan.jenis_laporan }}</p>

        <div class="flex justify-end">
          <a href="{% url 'petugas:tanggapan_tolak' pengaduan_id=pengaduan.id %}"
             class="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 transition duration-300 ease-in-out">
            Validasi Kembali
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

project/petugas_view/templates/petugas/tanggapan_form.html
{% extends 'base.html' %}

{% block contents %}
  <div class="container mx-auto p-8">
    <h2 class="text-4xl font-extrabold text-gray-900 text-center mb-8">Tanggapan untuk Pengaduan <br>{{ pengaduan.isi_aduan }}</h2>
    
    <form method="post" class="bg-white p-8 rounded-xl shadow-2xl border-2 border-lime-200">
      {% csrf_token %}
      
      <div class="mb-8">
        <label for="tanggapan" class="block text-2xl font-bold text-gray-800 mb-2">Tulis Tanggapan</label>
        {{ form.as_p }}
      </div>

      <button type="submit" class="w-full py-4 bg-lime-600 text-white font-semibold rounded-md shadow-lg hover:bg-lime-700 hover:shadow-xl transition duration-300 ease-in-out">
        Kirim Tanggapan
      </button>
    </form>
  </div>
{% endblock %}