project/auth_view/urls.py
from django.urls import path
from .views import (
  UserLoginView,
  UserRegisterView,
  UserLogoutView,

  PetugasLoginView,
  PetugasRegisterView,
  PetugasLogoutView,
)

urlpatterns = [
  path('login/', UserLoginView.as_view(), name="user_login"),
  path('register/', UserRegisterView.as_view(), name="user_register"),
  path('logout/', UserLogoutView.as_view(), name="user_logout"),

  path('petugas/login/', PetugasLoginView.as_view(), name='petugas_login'),
  path('petugas/register/', PetugasRegisterView.as_view(), name="petugas_register"),
  path('petugas/logout/', PetugasLogoutView.as_view(), name="petugas_logout"),
]

project/masyarakat_view/urls.py
from django.urls import path
from .views import (
  UserDashboardView,

  PengaduanHistoryListView,
  PengaduanCreateView,
  PengaduanDeleteView,
)

urlpatterns = [
  path('' , UserDashboardView.as_view(), name="user_dashboard"),

  path('pengaduan/history/', PengaduanHistoryListView.as_view(), name="pengaduan_history"),
  path('pengaduan/create/<int:jenis_laporan_id>', PengaduanCreateView.as_view(), name="pengaduan_create"),
  path('pengaduan/delete/<int:pk>', PengaduanDeleteView.as_view(), name="pengaduan_delete"),
]

project/petugas_view/urls.py
from django.urls import path
from .views import (
    PengaduanBelumTerjawabListView,
    TanggapanBelumTerjawabCreateView,
    PengaduanDesposisiListView,
    TanggapanDesposisiCreateView,
    PengaduanProsesListView,
    TanggapanProsesCreateView,
    PengaduanSelesaiListView,
    PengaduanTolakListView,
    TanggapanTolakView,
    TanggapanSelesaiCreateView,

    LogAktivitasPetugasListView,

    buat_pengaduan_dokumen,
)

urlpatterns = [
    path('', PengaduanBelumTerjawabListView.as_view(), name='petugas_dashboard'),
    path('tanggapan/belum-terjawab/<int:pengaduan_id>/', TanggapanBelumTerjawabCreateView.as_view(), name='tanggapan_belum_terjawab'),
    path('pengaduan/desposisi/', PengaduanDesposisiListView.as_view(), name='pengaduan_desposisi_view'),
    path('tanggapan/desposisi/<int:pengaduan_id>/', TanggapanDesposisiCreateView.as_view(), name='tanggapan_desposisi'),
    path('pengaduan/proses/', PengaduanProsesListView.as_view(), name='pengaduan_proses_view'),
    path('tanggapan/proses/<int:pengaduan_id>/', TanggapanProsesCreateView.as_view(), name='tanggapan_proses'),
    path('pengaduan/selesai/', PengaduanSelesaiListView.as_view(), name='pengaduan_selesai_view'),
    path('tanggapan/selesai/<int:pengaduan_id>/', TanggapanSelesaiCreateView.as_view(), name='tanggapan_selesai'),
    path('pengaduan/tolak/', PengaduanTolakListView.as_view(), name='pengaduan_tolak_view'),
    path('pengaduan/tanggapan/tolak/<int:pengaduan_id>/', TanggapanTolakView.as_view(), name='tanggapan_tolak'),

    path('log_aktivitas/' , LogAktivitasPetugasListView.as_view(), name="log_aktivitas_view"),

    path('pengaduan/generate_pdf/', buat_pengaduan_dokumen, name='buat_pengaduan_dokumen'),
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(('auth_view.urls', 'auth_view') , namespace="auth")),
    path('' , include(('masyarakat_view.urls', 'masyarakat_view'), namespace="masyarakat")),
    path('petugas/', include(('petugas_view.urls', 'petugas_view'), namespace="petugas")),
    path('dinas/', include(('petugas_view.urls', 'petugas_view'), namespace="dinas")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/templates/snippets/nav_admin.html
<!-- Navbar -->
<nav class="bg-gradient-to-br from-lime-200 shadow-md p-4">
  <div class="container mx-auto flex justify-between items-center">
    <a href="{% url 'petugas:petugas_dashboard' %}" class="text-3xl font-bold text-gray-800 hover:text-gray-900 transition-all duration-300">
      Petugas Dashboard
    </a>

    <div class="hidden md:flex space-x-6 items-center">
      <a href="{% url 'petugas:petugas_dashboard' %}" class="text-gray-700 hover:text-gray-900 transition duration-300 ease-in-out">Belum Terjawab</a>
      <a href="{% url 'petugas:pengaduan_desposisi_view' %}" class="text-gray-700 hover:text-gray-900 transition duration-300 ease-in-out">Desposisi</a>
      <a href="{% url 'petugas:pengaduan_proses_view' %}" class="text-gray-700 hover:text-gray-900 transition duration-300 ease-in-out">Proses</a>
      <a href="{% url 'petugas:pengaduan_selesai_view' %}" class="text-gray-700 hover:text-gray-900 transition duration-300 ease-in-out">Selesai</a>
      <a href="{% url 'petugas:pengaduan_tolak_view' %}" class="text-gray-700 hover:text-gray-900 transition duration-300 ease-in-out">Tolak</a>

      {% if request.user.level == 'admin' %}
      <a href="{% url 'petugas:log_aktivitas_view' %}" class="text-gray-700 hover:text-gray-900 transition duration-300 ease-in-out">Log Aktivitas</a>
      {% endif %}

      <form action="{% url 'auth:petugas_logout' %}" method="post" class="inline">
        {% csrf_token %}
        <button type="submit" class="text-gray-700 text-md hover:text-gray-800 ease-in-out">
          Logout
        </button>
      </form>
    </div>

    <div class="md:hidden flex items-center space-x-2">
      <button class="text-gray-700 hover:text-gray-900 transition duration-300 ease-in-out">
        <i class="fas fa-bars"></i>
      </button>
    </div>
  </div>
</nav>

project/templates/snippets/nav_user.html
<!-- Navbar -->
<nav class="bg-gradient-to-br from-lime-200 shadow-md mb-10">
  <div class="container mx-auto flex justify-between items-center py-4 px-6 relative bottom-3">
    <a href="{% url 'masyarakat:user_dashboard' %}" class="text-3xl font-semibold text-gray-800 hover:text-gray-900">
      {{header}}
    </a>

    <div class="flex items-center space-x-6">
      <a href="{% url 'masyarakat:user_dashboard' %}" class="text-lg text-gray-800 hover:text-gray-900">Home</a>
      <a href="{% url 'masyarakat:pengaduan_history' %}" class="text-lg text-gray-800 hover:text-gray-900">
        Riwayat Laporan
      </a>
      <form action="{% url 'auth:user_logout' %}" method="post" class="inline">
        {% csrf_token %}
        <button type="submit" class="text-gray-700 hover:text-gray-800 font-semibold rounded-lg transition duration-300 ease-in-out">
          Logout
        </button>
      </form>
    </div>
  </div>
</nav>